### ISSUE TITLE
branches  v0.3.0 can not build on rust 1.90 nightly

### ISSUE THREAD

**Issue by jinleili** [fereidani/branches#7]
https://github.com/fereidani/branches/issues/6 says this was fixed in 0.3, but the problem still happens when compiling on macOS:
```log
error[E0107]: function takes 1 generic argument but 2 generic arguments were supplied
   --> /Users/lijinlei/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/branches-0.3.0/src/lib.rs:187:23
    |
187 |     core::intrinsics::prefetch_read_data::<_, LOCALITY>(addr)
    |                       ^^^^^^^^^^^^^^^^^^    ---------- help: remove the unnecessary generic argument
    |                       |
    |                       expected 1 generic argument
    |
note: function defined here, with 1 generic parameter: `T`
   --> /Users/lijinlei/.rustup/toolchains/nightly-2025-08-01-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/intrinsics/mod.rs:280:15
    |
280 | pub unsafe fn prefetch_read_data<T>(data: *const T, locality: i32);
    |               ^^^^^^^^^^^^^^^^^^ -

error[E0061]: this function takes 2 arguments but 1 argument was supplied
   --> /Users/lijinlei/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/branches-0.3.0/src/lib.rs:187:5
    |
187 |     core::intrinsics::prefetch_read_data::<_, LOCALITY>(addr)
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^------ argument #2 of type `i32` is missing
    |
note: function defined here
   --> /Users/lijinlei/.rustup/toolchains/nightly-2025-08-01-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/intrinsics/mod.rs:280:15
    |
280 | pub unsafe fn prefetch_read_data<T>(data: *const T, locality: i32);
    |               ^^^^^^^^^^^^^^^^^^
help: provide the argument
    |
187 |     core::intrinsics::prefetch_read_data::<_, LOCALITY>(addr, /* i32 */)
    |                                                             +++++++++++

error[E0107]: function takes 1 generic argument but 2 generic arguments were supplied
   --> /Users/lijinlei/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/branches-0.3.0/src/lib.rs:241:23
    |
241 |     core::intrinsics::prefetch_write_data::<_, LOCALITY>(addr)
    |                       ^^^^^^^^^^^^^^^^^^^    ---------- help: remove the unnecessary generic argument
    |                       |
    |                       expected 1 generic argument
    |
note: function defined here, with 1 generic parameter: `T`
   --> /Users/lijinlei/.rustup/toolchains/nightly-2025-08-01-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/intrinsics/mod.rs:292:15
    |
292 | pub unsafe fn prefetch_write_data<T>(data: *const T, locality: i32);
    |               ^^^^^^^^^^^^^^^^^^^ -

error[E0061]: this function takes 2 arguments but 1 argument was supplied
   --> /Users/lijinlei/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/branches-0.3.0/src/lib.rs:241:5
    |
241 |     core::intrinsics::prefetch_write_data::<_, LOCALITY>(addr)
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^------ argument #2 of type `i32` is missing
    |
note: function defined here
   --> /Users/lijinlei/.rustup/toolchains/nightly-2025-08-01-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/intrinsics/mod.rs:292:15
    |
292 | pub unsafe fn prefetch_write_data<T>(data: *const T, locality: i32);
    |               ^^^^^^^^^^^^^^^^^^^
help: provide the argument
    |
241 |     core::intrinsics::prefetch_write_data::<_, LOCALITY>(addr, /* i32 */)
```
My Rust Nightly configuration is as follows:
```toml
[toolchain]
# rust 1.90 nightly
channel = "nightly-2025-08-01"
components = ["rust-src", "rustfmt", "clippy"]
targets = ["wasm32-unknown-unknown"]
profile = "minimal"
```

**Comment by fereidani** [comment]
Works fine with the latest nightly, like `rustc 1.92.0-nightly (52618eb33 2025-09-14)`, nightly API changed, so I followed the std library changes for branches. If you want to keep the old API, you need to depend on `branches 0.2`.
